# Generated by Django 2.2.14 on 2020-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse',
        ),
        migrations.AddField(
            model_name='commande',
            name='indication',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
