# Generated by Django 2.2.14 on 2021-02-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='status',
            new_name='etat',
        ),
    ]
