# Generated by Django 2.2.14 on 2021-03-02 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20210222_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
