# Generated by Django 2.2 on 2021-03-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_auto_20210302_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('Effectué', 'Commande effectuée'), ('En cours', 'Commande en cours de traitement'), ('Livrée', 'Commande livrée')], default='effectuee', max_length=10),
        ),
    ]
