# Generated by Django 2.2.14 on 2020-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201227_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='by_phone',
            field=models.BooleanField(default=True),
        ),
    ]
