# Generated by Django 2.2.14 on 2020-12-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_by_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='by_phone',
            field=models.BooleanField(default=False),
        ),
    ]
