# Generated by Django 2.2.14 on 2020-12-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201227_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='by_phone',
            field=models.BooleanField(default=True),
        ),
    ]
