# Generated by Django 2.2 on 2021-04-13 11:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201227_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
