# Generated by Django 2.2 on 2021-04-13 12:33

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210413_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
