# Generated by Django 2.2 on 2020-12-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0003_auto_20201201_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supcategorie',
            name='description',
            field=models.TextField(),
        ),
    ]
