# Generated by Django 2.2.14 on 2020-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0006_produit_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
