# Generated by Django 2.2.14 on 2020-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0007_auto_20201219_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('for_business', models.TextField()),
                ('free_liv', models.TextField()),
            ],
        ),
    ]
