# Generated by Django 2.2.14 on 2020-12-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0008_coordonnees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordonnees',
            new_name='Coordonnee',
        ),
    ]
