# Generated by Django 2.2.14 on 2020-12-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0009_auto_20201221_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordonnee',
            new_name='Info',
        ),
    ]
