# Generated by Django 2.2.14 on 2021-01-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0010_auto_20201221_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='homeslide/%y/%m/%d')),
                ('lien', models.CharField(max_length=20)),
            ],
        ),
    ]
